name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "latest"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./containers/cu
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kernel-computer-use:${{ github.event.inputs.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kernel-computer-use:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kernel-computer-use:buildcache,mode=max
